---
- hosts: localhost
  connection: local
  gather_facts: false
  become: true
  vars:
    # User to run ansible-pull as from cron
    cron_user: root

    # File that ansible will use for logs
    logfile: /Users/magnusducatuslt/spatium/ansible-pull/logs.txt

    # Directory to where repository will be cloned
    workdir: /Users/magnusducatuslt/spatium/ansible-pull

    repo_url: git@github.com:magnusducatuslt/ansible-pull.git
  tasks:
    - include_tasks: tasks/user.yaml
    - include_tasks: tasks/cron.yaml
    - include_tasks: tasks/docker.yaml
   