---
- hosts: 127.0.0.1
  connection: local
  become: true
  gather_facts: false
  vars:

    # schedule is fed directly to cron
    schedule: '* * * * *'

    # User to run ansible-pull as from cron
    cron_user: root

    # File that ansible will use for logs
    logfile: /Users/magnusducatuslt/spatium/ansible-pull/logs.txt

    # Directory to where repository will be cloned
    workdir: /Users/magnusducatuslt/spatium/ansible-pull

    repo_url: git@github.com:magnusducatuslt/ansible-pull.git
  tasks:
    - include_tasks: tasks/cron.yaml

    - name: "Execute"
      shell: "echo 1"
      register: output
    - debug: var=output.stdout_lines

    - name: Tear down existing services
      community.docker.docker_compose:
        project_src: "./"
        state: absent # Specifying absent is the same as running docker-compose down.
      register: "output"

    - name: Stop all services
      community.docker.docker_compose:
        project_src: ./
        build: false # Use with state present to always build images prior to starting the application.
        stopped: true # Use with state present to stop all containers defined in the Compose file.
      register: output

    - name: Create and start services
      community.docker.docker_compose:
        build: true # Use with state present to always build images prior to starting the application.
        state: present # Desired state of the project. Specifying present is the same as running docker-compose up resp.
        project_src: ./ # Path to a directory containing a docker-compose.yml or docker-compose.yaml file.
    