---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    # User to run ansible-pull as from cron
    cron_user: ansible

    # File that ansible will use for logs
    logfile: /Users/magnusducatuslt/spatium/ansible-pull/logs.txt

    # Directory to where repository will be cloned
    workdir: /Users/magnusducatuslt/spatium/ansible-pull

    repo_url: git@github.com:magnusducatuslt/ansible-pull.git
  tasks:
    - name: Create user
      user:
        name: "{{cron_user}}"
        system: yes
    - name: Allow the bob user to run any commands as alice with sudo -u alice
      community.general.sudoers:
        name: ansible-do-as-root
        state: present
        user: "{{cron_user}}"
        runas: root
        commands: ALL 
    - include_tasks: tasks/cron.yaml
    - include_tasks: tasks/docker.yaml
   