- name: install cronjob
  cron:
    user: "ansible"
    name: "ansible"
    minute: "*/1"
    job: "/opt/homebrew/bin/ansible-pull -o -U {{repo_url}} -i hosts --key-file ~.ssh/github --user magnusducatuslt >>{{ logfile }} 2>&1"