- name: install cronjob
  cron:
    user: "{{cron_user}}"
    name: "ansible"
    minute: "*/1"
    job: "/opt/homebrew/bin/ansible-pull -o -U {{repo_url}} -i hosts -e key-file=~.ssh/github >>{{ logfile }} 2>&1"